#!/bin/bash

set -e -x

export GOPATH=$PWD/gopath
export PATH=$GOPATH/bin:$PATH

go install github.com/vito/tracksuit

tracksuit \
  --github-token "$GITHUB_TOKEN" \
  --tracker-token "$TRACKER_TOKEN" \
  --project-id "$PROJECT_ID" \
  --organization "$ORGANIZATION" \
  --repositories "$REPOSITORIES" \
  --githuburl "$GITHUB_URL"

